### ISSUE TITLE
Ability to Play the Script

### ISSUE THREAD

**Issue by rlaphoenix** [quietvoid/vspreview-rs#10]
It would be great if you could play the script at the script's frame rate, with the ability to set a custom frame rate.

**Comment by quietvoid** [comment]
I have no use for this and it can be done by other software like mpv.

**Comment by rlaphoenix** [comment]
That is fair, but isn't this project about convenience? It's somewhat annoying to remember how to send a script to MPV via lavfi config commands, as well as the fact that often or not, you only want to temporarily play a bit just to see if queue or caching works, which cannot be tested by simply going frame by frame.

**Comment by adworacz** [comment]
Just adding in that being able to play back the script would be quite helpful when tuning things that incorporate things like deshaking or flicker removal, as seeing the impact of a change is pretty difficult on a single frame, but playing back the footage can very clearly identify the impact.

**Comment by quietvoid** [comment]
> it can be done by other software like mpv.
