### ISSUE TITLE
Restrict Image Bounds from the Seek Bar

### ISSUE THREAD

**Issue by rlaphoenix** [quietvoid/vspreview-rs#13]
The screenshot you have in the README would be a good example, but to work also for frames that have a larger height compared to the window.

This larger height would often happen with 4:3 material as you can see here:

![image](https://user-images.githubusercontent.com/17136956/156327277-c238edf0-08db-493c-b1e5-cd2df6eb3933.png)

**Comment by quietvoid** [comment]
I'm not going to fix this because I don't want the image to be scaled unnecessarily.
Just toggle the UI.
