### ISSUE TITLE
Messages does not hide when you hide GUI (`i` hotkey)

### ISSUE THREAD

**Issue by rlaphoenix** [quietvoid/vspreview-rs#17]
Before:

![image](https://user-images.githubusercontent.com/17136956/156333501-50f0bd49-1c47-4fc4-99af-1b61db07e187.png)

When `i` is pressed:

![image](https://user-images.githubusercontent.com/17136956/156333552-def1164f-15b1-4fcf-aa03-a1684f62cb6b.png)

* * *

I understand this may be intentional, though that isn't immediately clear so I thought I'd bring it up.

**Comment by quietvoid** [comment]
Not intentional, fixed it.
