### ISSUE TITLE
Does it work with AMD?

### ISSUE THREAD

**Issue by DomBito** [quietvoid/vspreview-rs#21]
I'm using Archlinux and AMD CPU+GPU.
Am I doing something wrong?

```
$ ./vspreview-rs script.py
mesa: CommandLine Error: Option 'reuse-storage-in-coroutine-frame' registered more than once!
LLVM ERROR: inconsistency in registered CommandLine options
zsh: IOT instruction (core dumped)  ./vspreview-rs script.py
```

**Comment by quietvoid** [comment]
It work fine on AMD.
Do you perhaps have the [vsakarin plugin](https://github.com/AkarinVS/vapoursynth-plugin) installed?

I had the same error before: https://github.com/AkarinVS/vapoursynth-plugin/issues/7#issuecomment-1031643815
The AUR package was never updated: https://aur.archlinux.org/packages/vapoursynth-plugin-vsakarin-git#comment-851049

**Comment by DomBito** [comment]
Unbelievable. I had it installed and uninstalling made it work!
Thank you!

**Comment by quietvoid** [comment]
The alternative is simply to rebuild it with the PKGBUILD modified:
```diff
diff --git a/PKGBUILD b/PKGBUILD
index 839aa78..f04b947 100644
--- a/PKGBUILD
+++ b/PKGBUILD
@@ -32,7 +32,8 @@ prepare(){
 build() {
   cd build
   arch-meson "../${_plug}" \
-    --buildtype=release
+    --buildtype=release \
+    -Dstatic-llvm=false
 
   ninja
 }
```
