### ISSUE TITLE
[Feature Request] Add in a second split separated view

### ISSUE THREAD

**Issue by BlueSwordM** [quietvoid/vspreview-rs#22]
Hello. I've just discovered vspreview-vs, and it's honestly been so nice using it, especially since building it was much easier vs normal VS-Preview, and it's nice and fast.

However, there is something that would be very nice to have inside of it: a split view in which you can load in a separate script to compare both images **side by side** to each other to see which VS scripts produces the highest fidelity/most appealing results.
That way, you could zoom across both panels simultaneously

Ideally, it would also be possible to take a screenshot of both viewports separated by the split view to make for easier screenshot comparisons later as well. That

Finally, a nice addition to this feature would be to be able to take the dual viewport screenshot feature, but of both the viewports in separate screenshots rather than both in split view for better later full frame comparisons.

Thank you and have a good day :D

**Comment by quietvoid** [comment]
I'm not interested in implementing such a feature. It doesn't really make sense.

What you can do already:
- Resize your clips and use StackHorizontal.
- Use multiple output nodes to switch between clips.
- Run two instances of `vspreview-rs` side by side.

**Comment by BlueSwordM** [comment]
Understood.

Thank you.
