### ISSUE TITLE
Implement a Log Window

### ISSUE THREAD

**Issue by rlaphoenix** [quietvoid/vspreview-rs#9]
The ability to log exceptions, print debug messages, generally log stuff and such in the GUI would be nice.

**Comment by quietvoid** [comment]
There is an error window but nothing for VS messages yet.

**Comment by quietvoid** [comment]
See example here: https://github.com/quietvoid/vspreview-rs/blob/main/UI.md#errormessage-window

It's only displayed if there are messages.
